version: '3.1'

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    restart: unless-stopped 
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    networks:
      - mynetwork
    volumes:
      - ./static:/static

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    env_file:
      - frontend/.env